# Generated by Django 3.2.12 on 2022-12-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_img', models.ImageField(upload_to='courses/%Y/%m/%d/')),
                ('course_name', models.CharField(max_length=30, unique=True, verbose_name='Kurs Adı')),
                ('course_detail', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
