# Generated by Django 3.2.12 on 2022-12-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(upload_to='courses/static/img'),
        ),
    ]
