# Generated by Django 3.2.12 on 2022-12-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(default='courses/courses-1.jpg', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
