# Generated by Django 3.2.12 on 2022-12-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20221204_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, default='courses/courses-1.jpg', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
