# Generated by Django 3.2.12 on 2022-12-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, default='courses/static/img/courses-1.jpg', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
