# Generated by Django 3.2.12 on 2022-12-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_Instructor',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=True),
        ),
    ]
