# Generated by Django 3.2.12 on 2022-12-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_price',
        ),
    ]
