# Generated by Django 3.2.12 on 2022-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.CharField(default='Free', max_length=10),
        ),
    ]
