# Generated by Django 3.2.12 on 2022-12-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_course_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skill_level',
            field=models.CharField(default='All Level', max_length=50),
        ),
    ]
