# Generated by Django 3.2.12 on 2022-12-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_course_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_Instructor',
        ),
    ]
