# Generated by Django 3.2.12 on 2022-12-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tatle', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='courses\\%Y\\%m\\%d')),
                ('facebook', models.URLField(blank=True, max_length=150)),
                ('instagram', models.URLField(blank=True, max_length=150)),
                ('twitter', models.URLField(blank=True, max_length=150)),
                ('linkedin', models.URLField(blank=True, max_length=150)),
            ],
        ),
    ]
