# Generated by Django 3.2.12 on 2022-12-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoniall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_done', models.CharField(max_length=100)),
                ('std_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
    ]
