# Generated by Django 3.2.12 on 2022-12-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_students'),
        ('eduapp', '0002_testimoniall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoniall',
            name='course_done',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course'),
        ),
    ]
