# Generated by Django 3.2.12 on 2022-12-09 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eduapp', '0003_alter_testimoniall_course_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoniall',
            name='std_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
